# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0003_deliveryitem_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitem',
            name='price_unit',
        ),
    ]
