# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_remove_deliveryitem_price_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('W', 'kr/kg'), ('U', 'kr/enhet')], default='W', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvester.CropForm')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_pricelist',
        ),
        migrations.RemoveField(
            model_name='deliveryitem',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='deliverysingle',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='name',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='customers',
            field=models.ManyToManyField(to='harvester.Customer'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='price_type',
            field=models.CharField(choices=[('W', 'kr/kg'), ('U', 'kr/enhet')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvester.PriceList'),
        ),
    ]
