# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0005_auto_20161025_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='pricelistitem',
            name='price_list',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='harvester.CustomerCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='harvester.CustomerCategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
