# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0006_auto_20161025_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='order_unit',
            field=models.CharField(choices=[('W', 'kr/kg'), ('U', 'kr/st')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='price_type',
            field=models.CharField(choices=[('W', 'kr/kg'), ('U', 'kr/st')], default='W', max_length=1),
        ),
    ]
