# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0007_auto_20161026_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropform',
            name='countable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='order_unit',
            field=models.CharField(choices=[('W', 'kg'), ('U', 'st')], default='U', max_length=1),
        ),
    ]
