# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0008_auto_20161026_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropform',
            name='is_default',
            field=models.NullBooleanField(default=None, unique=True),
        ),
    ]
